Update for 21.3.3
avadev/AvaTax-REST-V2-DotNet-SDK pull request #161
Opened 2021-05-25 10:39 UTC by ametaanshul

Update for 21.3.3

2021-05-27 11:23 UTC, svc-developer approved these changes

2021-06-23 19:15 UTC, greg-hester-avalara requested changes

2021-06-23 19:15 UTC, greg-hester-avalara commented on tests/net20/ExceptionRetryTest.cs
> +using System.Net.Http;
I'm getting a compiler error here when opening the .net20 project.
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0234	The type or namespace name 'Http' does not exist in the namespace 'System.Net' (are you missing an assembly reference?)	Tests.Avalara.AvaTax.net20	C:\Work Stuff\Avalara\AvaTax-REST-V2-DotNet-SDK\tests\net20\ExceptionRetryTest.cs	4	Active

2021-07-13 17:50 UTC, svc-developer commented
LGTM

2021-07-15 16:40 UTC, closed without merging